// Auth
export const LOADING_GET_USER_TYPE = 'LOADING_GET_USER_TYPE';
export const GOT_USER_TYPE = 'GOT_USER_TYPE';
export const GOT_USER_TYPE_FAILED = 'GOT_USER_TYPE_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
// change password
export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

// Error handling and feedback UI reports
export const CREATE_MESSAGES = 'CREATE_MESSAGES';
export const API_MESSSAGE = 'API_MESSSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

// Battalion Two CRUD
export const BATTALLION_TWO_CREATE = 'BATTALLION_TWO_CREATE';
export const BATTALLION_TWO_CREATE_LOADING = 'BATTALLION_TWO_CREATE_LOADING';
export const BATTALLION_TWO_CREATED = 'BATTALLION_TWO_CREATED';

// Fetching battalion two data
export const BATTALION_TWO_OVERRALL_FETCHED = 'BATTALION_TWO_OVERRALL_FETCHED';
export const BATTALION_TWO_DATA_FETCHED = 'BATTALION_TWO_DATA_FETCHED';
export const BATTALION_TWO_DATA_LOADING = 'BATTALION_TWO_DATA_LOADING';

export const BATTALION_TWO_DETAIL_LOADING = 'BATTALION_TWO_DETAIL_LOADING';
export const BATTALION_TWO_DETAIL_FETCHED = 'BATTALION_TWO_DETAIL_FETCHED';

export const BATTALION_TWO_QUERY_LOADING = 'BATTALION_TWO_QUERY_LOADING';
export const BATTALION_TWO_QUERY_FETCHED = 'BATTALION_TWO_QUERY_FETCHED';
export const BATTALION_TWO_QUERY_FAILED = 'BATTALION_TWO_QUERY_FAILED';

// Fetching battalion one data
export const BATTALION_ONE_DATA_LOADING = 'BATTALION_ONE_DATA_LOADING';
export const BATTALION_ONE_DATA_FETCHED = 'BATTALION_ONE_DATA_FETCHED';

export const BATTALION_ONE_DETAIL_LOADING = 'BATTALION_ONE_DETAIL_LOADING';
export const BATTALION_ONE_DETAIL_FETCHED = 'BATTALION_ONE_DETAIL_FETCHED';

export const BATTALION_SECTION_QUERY_LOADING = 'BATTALION_SECTION_QUERY_LOADING';
export const BATTALION_SECTION_QUERY_FETCHED = 'BATTALION_SECTION_QUERY_FETCHED';

export const GENERATE_REPORT_BATTALLION_TWO_LOADING = 'GENERATE_REPORT_BATTALLION_TWO_LOADING';
export const GENERATE_REPORT_BATTALLION_TWO_DONE = 'GENERATE_REPORT_BATTALLION_TWO_DONE';
